Create Seed template
frees-io/freestyle-seed.g8 pull request #1
Opened 2017-06-24 04:18 UTC by AdrianRaFo

2017-06-24 10:46 UTC, juanpedromoreno requested changes

2017-06-24 10:46 UTC, juanpedromoreno commented on README.md
> +sbt orgCreateFiles
This is not valid since we're not using sbt-org-policies plugin.

2017-06-24 10:46 UTC, juanpedromoreno commented on README.md
> +sbt orgScriptCI
Same here

2017-06-24 10:46 UTC, juanpedromoreno commented on README.md
> +## Creating New Freestyle Project
I'd update the steps in this file to be aligned what we are providing with this g8 template.

2017-06-24 10:46 UTC, juanpedromoreno commented on src/main/g8/.scalafmt.conf
> +style = defaultWithAlign
I'd suggest either removing this scalafmt file or providing a basic sbt configuration to make this file valid

2017-06-24 10:46 UTC, juanpedromoreno commented on src/main/g8/build.sbt
> +pgpSecretRing := file(s"$gpgFolder/secring.gpg")
These three setting keys can be removed

2017-06-24 10:46 UTC, juanpedromoreno commented on src/main/g8/build.sbt
> +  .settings(noPublishSettings: _*)
You need to define noPublishSettings, otherwise it won't work

2017-06-25 00:51 UTC, raulraja commented
This is awesome.  It should include the same license as the rest of the modules in the frees.io organization. Also Maureen may want to take a pass at the text for review. Thanks Adri! @juanpedromoreno anything to add?

2017-06-25 05:05 UTC, juanpedromoreno approved these changes
LGTM, thanks so much!

2017-06-25 11:51 UTC, AdrianRaFo commented
@raulraja The freestyle template doesn't include the `LICENSE` file, should it include it too?

2017-06-25 12:33 UTC, raulraja commented
Not the template but the actual g8 template project

On Sun, Jun 25, 2017, 1:51 PM Adrián Ramírez Fornell <
notifications@github.com> wrote:

> @raulraja <https://github.com/raulraja> The freestyle template doesn't
> include the LICENSE file, should it include it too?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/frees-io/freestyle-seed.g8/pull/1#issuecomment-310898272>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAb4XKFuJx1T6bHXLrpzToccFAShLI7Xks5sHkm0gaJpZM4OEN8x>
> .
>

2017-06-25 14:07 UTC, AdrianRaFo commented
@raulraja what I wanted to say was that I going to add the LICENSE to this project but the freestyle-template.g8 project doesn't have a LICENSE and I think that it should have it

2017-06-30 14:02 UTC, juanpedromoreno approved these changes
👍

2017-06-30 14:02 UTC, merged